<%@ page language="C#" autoeventwireup="true" CodeFile="Default4.aspx.cs" Inherits="Default4" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>VERIFICATION SAISIE</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <a href="Default.aspx">MENU</a>
            <br />
            <br />
            <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged">
                <asp:ListItem Value="" Selected="True"></asp:ListItem>
                <asp:ListItem Value="S1"></asp:ListItem>
                <asp:ListItem Value="S2"></asp:ListItem>
                <asp:ListItem Value="S3"></asp:ListItem>
                <asp:ListItem Value="S4"></asp:ListItem>
           </asp:DropDownList>
            <asp:GridView Visible="false" ID="G_S1" runat="server" DataSourceID="S1" />
            <asp:GridView Visible="false" ID="G_S2" runat="server" DataSourceID="S2" />
            <asp:GridView Visible="false" ID="G_S3" runat="server" DataSourceID="S3" />
            <asp:GridView Visible="false" ID="G_S4" runat="server" DataSourceID="S4" />
             
           <asp:SqlDataSource OnSelecting="S1_Selecting" ID="S1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
                SelectCommand="
DECLARE @SERIE VARCHAR(50)
SET @SERIE = '1'
SELECT SS.JURY, CASE WHEN MAX(CASE WHEN SS.JURE=1 THEN 1 ELSE 0 END)=0
THEN '1' ELSE '_' END +
CASE WHEN MAX(CASE WHEN SS.JURE=2 THEN 1 ELSE 0 END)=0
THEN '2' ELSE '_' END +
CASE WHEN MAX(CASE WHEN SS.JURE=3 THEN 1 ELSE 0 END)=0
THEN '3' ELSE '_' END +
CASE WHEN MAX(CASE WHEN SS.JURE=4 THEN 1 ELSE 0 END)=0
THEN '4' ELSE '_' END As JURE_MANQUANT 
INTO #TABLE
FROM 
(SELECT DISTINCT JURY, JURE FROM SAISIE_SERIE ) SS,
(SELECT DISTINCT JURY, @SERIE SPECIAL FROM LISTE_VINS WHERE @SERIE in ('1','2','3','4') GROUP BY JURY ) LV
WHERE 
CASE WHEN @SERIE = '1' AND SS.JURY BETWEEN 1000 AND 1100 THEN 1
WHEN @SERIE = '2' AND SS.JURY BETWEEN 2000 AND 2100 THEN 1
WHEN @SERIE = '3' AND SS.JURY BETWEEN 1100 AND 1300 THEN 1
WHEN @SERIE = '4' AND SS.JURY BETWEEN 2100 AND 2300 THEN 1
WHEN @SERIE not in ('1','2','3','4') THEN 1
ELSE 0
END = 1
AND SS.JURY = LV.JURY
GROUP BY SS.JURY
HAVING COUNT(*) <> 4
ORDER BY SS.JURY
INSERT INTO #TABLE
SELECT DISTINCT JURY, '1234' 
FROM LISTE_VINS LV
where CASE WHEN @SERIE = '1' AND LV.JURY BETWEEN 1000 AND 1100 THEN 1
WHEN @SERIE = '2' AND LV.JURY BETWEEN 2000 AND 2100 THEN 1
WHEN @SERIE = '3' AND LV.JURY BETWEEN 1100 AND 1300 THEN 1
WHEN @SERIE = '4' AND LV.JURY BETWEEN 2100 AND 2300 THEN 1
WHEN @SERIE not in ('1','2','3','4') THEN 1
ELSE 0
END = 1
AND JURY NOT IN (
SELECT JURY FROM SAISIE_SERIE WHERE
CASE WHEN @SERIE = '1' AND LV.JURY BETWEEN 1000 AND 1100 THEN 1
WHEN @SERIE = '2' AND LV.JURY BETWEEN 2000 AND 2100 THEN 1
WHEN @SERIE = '3' AND LV.JURY BETWEEN 1100 AND 1300 THEN 1
WHEN @SERIE = '4' AND LV.JURY BETWEEN 2100 AND 2300 THEN 1
WHEN @SERIE not in ('1','2','3','4') THEN 1
ELSE 0
END = 1)
GROUP BY ORDRE, JURY
SELECT JURY, JURE_MANQUANT FROM #TABLE ORDER BY JURY
DROP TABLE #TABLE
">
            </asp:SqlDataSource>
         <asp:SqlDataSource OnSelecting="S2_Selecting" ID="S2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
             SelectCommand="
DECLARE @SERIE VARCHAR(50)
SET @SERIE = '2'
SELECT SS.JURY, CASE WHEN MAX(CASE WHEN SS.JURE=1 THEN 1 ELSE 0 END)=0
THEN '1' ELSE '_' END +
CASE WHEN MAX(CASE WHEN SS.JURE=2 THEN 1 ELSE 0 END)=0
THEN '2' ELSE '_' END +
CASE WHEN MAX(CASE WHEN SS.JURE=3 THEN 1 ELSE 0 END)=0
THEN '3' ELSE '_' END +
CASE WHEN MAX(CASE WHEN SS.JURE=4 THEN 1 ELSE 0 END)=0
THEN '4' ELSE '_' END As JURE_MANQUANT 
INTO #TABLE
FROM 
(SELECT DISTINCT JURY, JURE FROM SAISIE_SERIE ) SS,
(SELECT DISTINCT JURY, @SERIE SPECIAL FROM LISTE_VINS WHERE @SERIE in ('1','2','3','4') GROUP BY JURY ) LV
WHERE 
CASE WHEN @SERIE = '1' AND SS.JURY BETWEEN 1000 AND 1100 THEN 1
WHEN @SERIE = '2' AND SS.JURY BETWEEN 2000 AND 2100 THEN 1
WHEN @SERIE = '3' AND SS.JURY BETWEEN 1100 AND 1300 THEN 1
WHEN @SERIE = '4' AND SS.JURY BETWEEN 2100 AND 2300 THEN 1
WHEN @SERIE not in ('1','2','3','4') THEN 1
ELSE 0
END = 1
AND SS.JURY = LV.JURY
GROUP BY SS.JURY
HAVING COUNT(*) <> 4
ORDER BY SS.JURY
INSERT INTO #TABLE
SELECT DISTINCT JURY, '1234' 
FROM LISTE_VINS LV
where CASE WHEN @SERIE = '1' AND LV.JURY BETWEEN 1000 AND 1100 THEN 1
WHEN @SERIE = '2' AND LV.JURY BETWEEN 2000 AND 2100 THEN 1
WHEN @SERIE = '3' AND LV.JURY BETWEEN 1100 AND 1300 THEN 1
WHEN @SERIE = '4' AND LV.JURY BETWEEN 2100 AND 2300 THEN 1
WHEN @SERIE not in ('1','2','3','4') THEN 1
ELSE 0
END = 1
AND JURY NOT IN (
SELECT JURY FROM SAISIE_SERIE WHERE
CASE WHEN @SERIE = '1' AND LV.JURY BETWEEN 1000 AND 1100 THEN 1
WHEN @SERIE = '2' AND LV.JURY BETWEEN 2000 AND 2100 THEN 1
WHEN @SERIE = '3' AND LV.JURY BETWEEN 1100 AND 1300 THEN 1
WHEN @SERIE = '4' AND LV.JURY BETWEEN 2100 AND 2300 THEN 1
WHEN @SERIE not in ('1','2','3','4') THEN 1
ELSE 0
END = 1)
GROUP BY ORDRE, JURY
SELECT JURY, JURE_MANQUANT FROM #TABLE ORDER BY JURY
DROP TABLE #TABLE
">
            </asp:SqlDataSource>
         <asp:SqlDataSource OnSelecting="S3_Selecting" ID="S3" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
                SelectCommand="
DECLARE @SERIE VARCHAR(50)
SET @SERIE = '3'
SELECT SS.JURY, CASE WHEN MAX(CASE WHEN SS.JURE=1 THEN 1 ELSE 0 END)=0
THEN '1' ELSE '_' END +
CASE WHEN MAX(CASE WHEN SS.JURE=2 THEN 1 ELSE 0 END)=0
THEN '2' ELSE '_' END +
CASE WHEN MAX(CASE WHEN SS.JURE=3 THEN 1 ELSE 0 END)=0
THEN '3' ELSE '_' END +
CASE WHEN MAX(CASE WHEN SS.JURE=4 THEN 1 ELSE 0 END)=0
THEN '4' ELSE '_' END As JURE_MANQUANT 
INTO #TABLE
FROM 
(SELECT DISTINCT JURY, JURE FROM SAISIE_SERIE ) SS,
(SELECT DISTINCT JURY, @SERIE SPECIAL FROM LISTE_VINS WHERE @SERIE in ('1','2','3','4') GROUP BY JURY ) LV
WHERE 
CASE WHEN @SERIE = '1' AND SS.JURY BETWEEN 1000 AND 1100 THEN 1
WHEN @SERIE = '2' AND SS.JURY BETWEEN 2000 AND 2100 THEN 1
WHEN @SERIE = '3' AND SS.JURY BETWEEN 1100 AND 1300 THEN 1
WHEN @SERIE = '4' AND SS.JURY BETWEEN 2100 AND 2300 THEN 1
WHEN @SERIE not in ('1','2','3','4') THEN 1
ELSE 0
END = 1
AND SS.JURY = LV.JURY
GROUP BY SS.JURY
HAVING COUNT(*) <> 4
ORDER BY SS.JURY
INSERT INTO #TABLE
SELECT DISTINCT JURY, '1234' 
FROM LISTE_VINS LV
where CASE WHEN @SERIE = '1' AND LV.JURY BETWEEN 1000 AND 1100 THEN 1
WHEN @SERIE = '2' AND LV.JURY BETWEEN 2000 AND 2100 THEN 1
WHEN @SERIE = '3' AND LV.JURY BETWEEN 1100 AND 1300 THEN 1
WHEN @SERIE = '4' AND LV.JURY BETWEEN 2100 AND 2300 THEN 1
WHEN @SERIE not in ('1','2','3','4') THEN 1
ELSE 0
END = 1
AND JURY NOT IN (
SELECT JURY FROM SAISIE_SERIE WHERE
CASE WHEN @SERIE = '1' AND LV.JURY BETWEEN 1000 AND 1100 THEN 1
WHEN @SERIE = '2' AND LV.JURY BETWEEN 2000 AND 2100 THEN 1
WHEN @SERIE = '3' AND LV.JURY BETWEEN 1100 AND 1300 THEN 1
WHEN @SERIE = '4' AND LV.JURY BETWEEN 2100 AND 2300 THEN 1
WHEN @SERIE not in ('1','2','3','4') THEN 1
ELSE 0
END = 1)
GROUP BY ORDRE, JURY
SELECT JURY, JURE_MANQUANT FROM #TABLE ORDER BY JURY
DROP TABLE #TABLE
">
            </asp:SqlDataSource>
         <asp:SqlDataSource OnSelecting="S4_Selecting" ID="S4" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
                SelectCommand="
DECLARE @SERIE VARCHAR(50)
SET @SERIE = '4'
SELECT SS.JURY, CASE WHEN MAX(CASE WHEN SS.JURE=1 THEN 1 ELSE 0 END)=0
THEN '1' ELSE '_' END +
CASE WHEN MAX(CASE WHEN SS.JURE=2 THEN 1 ELSE 0 END)=0
THEN '2' ELSE '_' END +
CASE WHEN MAX(CASE WHEN SS.JURE=3 THEN 1 ELSE 0 END)=0
THEN '3' ELSE '_' END +
CASE WHEN MAX(CASE WHEN SS.JURE=4 THEN 1 ELSE 0 END)=0
THEN '4' ELSE '_' END As JURE_MANQUANT 
INTO #TABLE
FROM 
(SELECT DISTINCT JURY, JURE FROM SAISIE_SERIE ) SS,
(SELECT DISTINCT JURY, @SERIE SPECIAL FROM LISTE_VINS WHERE @SERIE in ('1','2','3','4') GROUP BY JURY ) LV
WHERE 
CASE WHEN @SERIE = '1' AND SS.JURY BETWEEN 1000 AND 1100 THEN 1
WHEN @SERIE = '2' AND SS.JURY BETWEEN 2000 AND 2100 THEN 1
WHEN @SERIE = '3' AND SS.JURY BETWEEN 1100 AND 1300 THEN 1
WHEN @SERIE = '4' AND SS.JURY BETWEEN 2100 AND 2300 THEN 1
WHEN @SERIE not in ('1','2','3','4') THEN 1
ELSE 0
END = 1
AND SS.JURY = LV.JURY
GROUP BY SS.JURY
HAVING COUNT(*) <> 4
ORDER BY SS.JURY
INSERT INTO #TABLE
SELECT DISTINCT JURY, '1234' 
FROM LISTE_VINS LV
where CASE WHEN @SERIE = '1' AND LV.JURY BETWEEN 1000 AND 1100 THEN 1
WHEN @SERIE = '2' AND LV.JURY BETWEEN 2000 AND 2100 THEN 1
WHEN @SERIE = '3' AND LV.JURY BETWEEN 1100 AND 1300 THEN 1
WHEN @SERIE = '4' AND LV.JURY BETWEEN 2100 AND 2300 THEN 1
WHEN @SERIE not in ('1','2','3','4') THEN 1
ELSE 0
END = 1
AND JURY NOT IN (
SELECT JURY FROM SAISIE_SERIE WHERE
CASE WHEN @SERIE = '1' AND LV.JURY BETWEEN 1000 AND 1100 THEN 1
WHEN @SERIE = '2' AND LV.JURY BETWEEN 2000 AND 2100 THEN 1
WHEN @SERIE = '3' AND LV.JURY BETWEEN 1100 AND 1300 THEN 1
WHEN @SERIE = '4' AND LV.JURY BETWEEN 2100 AND 2300 THEN 1
WHEN @SERIE not in ('1','2','3','4') THEN 1
ELSE 0
END = 1)
GROUP BY ORDRE, JURY
SELECT JURY, JURE_MANQUANT FROM #TABLE ORDER BY JURY
DROP TABLE #TABLE
">
            </asp:SqlDataSource>
              </div>
    </form>
</body>
</html>
